Repository nuxeo/doc.nuxeo.com-content, pull requests merged in 2019-02, with the labels that each got.

#1028 NXDOC-1826: reference PostgreSQL TLS/SSL documentation
  src/nxdoc/nuxeo-server/administration/database-configuration/postgresql.md
Labels: Reviewed

#1002 NXDOC-1770 Document Status Bar
  assets/studio/branch-management/commit_popup.png
  assets/studio/branch-management/discard-popup.png
  assets/studio/branch-management/push_popup.png
  assets/studio/branch-management/status-bar-studio.png
  assets/studio/commit-preferences/sources-management.png
  assets/studio/how-to-collaborate-on-a-studio-project/pull_popup.png
  assets/studio/how-to-collaborate-on-a-studio-project/simple_save_mode.png
  assets/studio/how-to-collaborate-on-a-studio-project/sources-management.png
  assets/studio/how-to-review-nuxeo-studio-configuration/push.png
  assets/studio/how-to-review-nuxeo-studio-configuration/revert-push.png
  assets/studio/how-to-review-nuxeo-studio-configuration/revert.png
  assets/studio/how-to-review-nuxeo-studio-configuration/wip.png
  assets/studio/studio-icons-index/commit.png
  assets/studio/studio-icons-index/delete.png
  assets/studio/studio-icons-index/pull.png
  assets/studio/studio-icons-index/push.png
  src/studio/nuxeo-studio/tutorials/how-to-collaborate-on-a-studio-project.md
  src/studio/nuxeo-studio/tutorials/how-to-review-nuxeo-studio-configuration.md
  src/studio/nuxeo-studio/tutorials/installing-the-studio-jar-manually.md
  src/studio/nuxeo-studio/working-in-studio/branch-management.md
  src/studio/nuxeo-studio/working-in-studio/branch-management/commit-push-and-pull.md
  src/studio/nuxeo-studio/working-in-studio/commit-preferences.md
Labels: Reviewing, Wait before merge

#1031 NXDOC-1818 Folderish Documents Configuration
  assets/nxdoc/how-to-display-children-documents-listing/edit-icon.png
  src/nxdoc/web-ui/web-ui-tutorials/how-to-display-children-documents-listing.md
  src/nxdoc/web-ui/web-ui-tutorials/web-ui-document-layouts.md
Labels: Pending Review, Wait before merge

#1042 NXP-26630: document new property
  src/nxdoc/nuxeo-server/administration/configuration-parameters-index-nuxeoconf.md
Labels: Reviewed

#1043 NXP-26630: document new property
  src/nxdoc/nuxeo-server/administration/configuration-parameters-index-nuxeoconf.md
Labels: Reviewed

#1034 Sample Workflow Configuration updated
  src/nxdoc/getting-started/workflow-tutorials/simple-workflow-example.md
Labels: Reviewed

#1048 Update webengine-jax-rs.md
  src/nxdoc/nuxeo-server/core-server/webengine-jax-rs.md
Labels: Reviewed

#1044 NXP-26518: Add shared secret documentation
  src/nxdoc/nuxeo-add-ons/nuxeo-arender-connector.md
Labels: Reviewed

#1045 NXP-26518: Add shared secret documentation
  src/nxdoc/nuxeo-add-ons/nuxeo-arender-connector.md
Labels: Reviewed

#1052 Update webengine-jax-rs.md
  src/nxdoc/nuxeo-server/core-server/webengine-jax-rs.md
Labels: Reviewed

#1051 Update howto-contribute-to-the-rest-api.md
  src/nxdoc/nuxeo-server/rest-api/rest-api-howtos/howto-contribute-to-the-rest-api.md
Labels: Reviewed

#1049 Update howto-upload-file-nuxeo-using-rest-api.md
  src/nxdoc/nuxeo-server/rest-api/rest-api-howtos/howto-upload-file-nuxeo-using-rest-api.md
Labels: Reviewed

#1056 Backport Update web-object-model.md PR 1053-9.10
  src/nxdoc/nuxeo-server/webengine-jax-rs/webengine-tutorials/web-object-model.md
Labels: Reviewed

#1055 Backport Update web-object-model.md PR 1053-10.10
  src/nxdoc/nuxeo-server/core-server/webengine-jax-rs/webengine-tutorials/web-object-model.md
Labels: Reviewed

#1057 Add Kafka to compatibility matrix for LTS 2017
  src/nxdoc/nuxeo-server/installation/compatibility-matrix.md
Labels: Reviewed

#1050 NXDOC-1444: Simplify WebUI customization tutorial to avoid DAM implementation details
  assets/nxdoc/web-ui-customization-tutorial/mime_type.png
  assets/nxdoc/web-ui-customization-tutorial/my_document_action.png
  assets/nxdoc/web-ui-customization-tutorial/my_document_action_popup.png
  src/nxdoc/web-ui/web-ui-tutorials/web-ui-customization-tutorial.md
Labels: Reviewed

#1059 Update Intellij IDEA setup page
  src/corg/developer-environment-setup/intellij-idea-setup.md
Labels: Reviewed

#1062 Style update for clarity.
  src/nxdoc/nuxeo-server/administration/database-configuration/mongodb.md
Labels: Reviewed

#1061 Simflofy Doc Update
  src/nxdoc/nuxeo-add-ons/nuxeo-simflofy-connector.md
Labels: Reviewed

#1060 NXDOC-1445: Update WebUI QA documentation to reflect Polymer 2 migration
  src/nxdoc/web-ui/nuxeo-elements/quality-assurance.md
Labels: Reviewed
