Repository nuxeo/doc.nuxeo.com-content, pull requests merged in 2019-08, with the labels that each got.

#1213 NXDOC-1927: expose the elastic more like this hint
  src/nxdoc/nuxeo-server/data-store/indexing-and-query/nxql.md
Labels: Pending Review

#1230 NXDOC-1961: 3.17 deployment, archive july changes
  src/studio/nuxeo-studio/nuxeo-studio-release-notes.md
  src/studio/nuxeo-studio/nuxeo-studio-release-notes/studio-updates-2019-05-and-06.md
  src/studio/nuxeo-studio/nuxeo-studio-release-notes/studio-updates-2019-07.md
Labels: Reviewed

#1229 NXDOC-1925 - More info on follow a single wf transition
  src/studio/nuxeo-studio/working-in-studio/workflow/node-popup/node-transitions-tab.md
Labels: Pending Review

#1219 Add some precision to express security policy
  src/nxdoc/nuxeo-server/data-store/security/security-policy-service.md
Labels: Pending Review

#1224 NXP-27864: remove nuxeo-connect-report-tools
  src/nxdoc/getting-started/best-practices/nuxeo-platform-feature-table.md
  src/nxdoc/nuxeo-add-ons.md
  src/nxdoc/nuxeo-add-ons/nuxeo-connect-report-tools.md
Labels: Reviewing
