Repository nuxeo/doc.nuxeo.com-content, pull requests merged in 2019-03, with the labels that each got.

#1063 NXDOC-1816 Studio Theme Override
  src/nxdoc/web-ui/web-ui-tutorials/web-ui-theme-customization.md
Labels: Reviewed

#1072 Add a bit more details to some commands
  src/nxdoc/nuxeo-tools/nuxeo-cli.md
Labels: Reviewed

#1074 NXDOC-1450: Review CLI develop page
  src/nxdoc/getting-started/develop-with-nuxeo-platform.md
Labels: Reviewed

#1015 NXDOC-1660 Update Application Definition - Package Installation Master
  src/nxdoc/nuxeo-add-ons/installing-a-new-package-on-your-instance.md
Labels: Pending Review

#1084 Fix error in direct upload example config
  src/nxdoc/nuxeo-add-ons/amazon-s3-online-storage.md
Labels: Reviewed

#1064 NXDOC-1816 Add link to how to Customize Themes
  src/studio/nuxeo-studio/working-in-view-designer/ui-designer.md
Labels: Reviewed, Wait before merge

#1058 Add info on Application Logo
  src/studio/nuxeo-studio/working-in-studio/branding.md
Labels: Reviewed, Wait before merge

#1067 NXDOC-1816 Studio Theme Override in Studio doc
  src/studio/nuxeo-studio/tutorials/how-to-customize-theme-studio.md
Labels: Reviewed, Wait before merge, studio-3.7.0

#1069 NXDOC-1852 Override Default Web UI configuration
  src/studio/nuxeo-studio/tutorials/how-to-override-default-contributions.md
Labels: Reviewed, Wait before merge, studio-3.7.0

#1073 NXDOC-1817 Update HOWTO with mapping of parameters
  src/nxdoc/web-ui/web-ui-tutorials/how-to-display-children-documents-listing.md
Labels: Reviewed, Wait before merge

#1078 Add Notes for HF02
  src/nxdoc/nuxeo-server/administration/monitoring-and-maintenance/hotfixes-installation-notes-for-nuxeo-platform-lts-2019.md
Labels: Reviewed

#1086 NXDOC-1568: Update page How to Override Existing Document Types
  src/nxdoc/nuxeo-server/core-server/content-repository/content-repository-tutorials/how-to-override-existing-document-types.md
Labels: Reviewed

#1087 NXDOC-1453: Review repository configuration page
  src/nxdoc/nuxeo-server/administration/repository-configuration.md
Labels: Reviewing

#1075 NXDOC-1853 Rename drawer options static
  src/studio/nuxeo-studio/administering-your-project/naming-conventions.md
  src/studio/nuxeo-studio/working-in-view-designer/ui-designer.md
Labels: Reviewed, studio-3.8.0

#1076 NXDOC-1853 Rename drawer actions master
  src/nxdoc/web-ui/web-ui-tutorials/web-ui-search.md
Labels: Reviewed, studio-3.8.0

#1016 NXDOC-1660 Update Application Definition - Package Installation Static
  src/studio/nuxeo-studio/working-in-studio/application-definition.md
Labels: Pending Review

#1095 NXDOC-1882 upcoming studio 3.9.0 draft, studio 3.8.0 release
  src/studio/nuxeo-studio/nuxeo-studio-release-notes.md
  src/studio/nuxeo-studio/nuxeo-studio-release-notes/studio-updates-2019-03.md
Labels: Reviewed
