Repository nuxeo/doc.nuxeo.com-content, pull requests merged in 2019-01, with the labels that each got.

#942 NXP-26423: Update documentation after VersioningService deprecation
  src/nxdoc/nuxeo-server/core-server/content-repository/versioning.md
Labels: Wait before merge

#967 RELEASE-802: Update dependencies
  src/nxdoc/getting-started/discover-nuxeo-platform-apis/setting-up-your-nuxeo-environment.md
Labels: Merge for 10.10

#964 NXDOC-1787: document s3 direct upload new parameters
  src/nxdoc/nuxeo-add-ons/amazon-s3-online-storage.md
Labels: Merge for 10.10

#976 NXDOC-1811: Put note on deprecated addon for 10.10
  src/nxdoc/generic-multi-excerpts.md
  src/nxdoc/nuxeo-add-ons/nuxeo-edge-cache.md
  src/nxdoc/nuxeo-add-ons/nuxeo-for-salesforce.md
  src/nxdoc/nuxeo-add-ons/nuxeo-jsf-ui.md
  src/nxdoc/nuxeo-add-ons/nuxeo-media-publishing.md
  src/nxdoc/nuxeo-server/administration/database-configuration/marklogic.md
Labels: Merge for 10.10, Wait before merge
