Repository nuxeo/doc.nuxeo.com-content, pull requests merged in 2019-11, with the labels that each got.

#1303 Update nuxeo-studio-community-cookbook.md
  src/studio/nuxeo-studio/nuxeo-studio-community-cookbook.md
Labels: Reviewed

#1296 NXDOC-1896: task widget refresh
  src/nxdoc/nuxeo-server/platform-services/workflow/workflow-how-to-index/how-to-refresh-the-task-widget-on-the-summary-tab.md
Labels: Reviewed

#1302 NXDOC-1989-fix-notification-emails-configuration-910
  src/nxdoc/nuxeo-server/events-and-listeners/how-to-customize-email-templates.md
  src/nxdoc/nuxeo-server/jsf-ui-framework/jsf-ui-how-to-index/how-to-make-jsf-ui-the-default-ui.md
Labels: Pending Review

#1318 NXDOC-2023: studio 3.21 release
  src/studio/nuxeo-studio/nuxeo-studio-release-notes.md
  src/studio/nuxeo-studio/nuxeo-studio-release-notes/studio-updates-2019-10-11.md
Labels: Reviewing

#1335 NXDOC-1968: document how to disable trash web ui side
  src/nxdoc/web-ui/web-ui-tutorials/how-to-disable-trash.md
Labels: Reviewed

#1337 NXDOC-1968: document how to disable trash web ui side
  src/nxdoc/web-ui/web-ui-tutorials/how-to-disable-trash.md
Labels: Reviewed

#1313 NXDOC-2016: How To Display Related Documents
  src/nxdoc/nuxeo-server/platform-services/automation/automation-how-to-index/howto-manage-relations.md
Labels: Wait before merge

#1328 NXDOC-2010 - how to set the Enhanced Viewer as default viewer
  src/nxdoc/nuxeo-add-ons/nuxeo-enhanced-viewer/how-to-set-enhanced-viewer-as-default-document-preview.md
Labels: Reviewing
