Repository nuxeo/doc.nuxeo.com-content, pull requests merged in 2020-12, with the labels that each got.

#1606 NXDOC-2210: Document Drive release cycle process
  src/client-apps/nuxeo-drive/nuxeo-drive-release-cycle.md
Labels: Ready for Review

#1618 NXDRIVE-2312: Documente the required KB for out-of-date Windows versions
  src/client-apps/nuxeo-drive/nuxeo-drive-faq.md
Labels: Ready for Review, Reviewing

#1643 NXDRIVE-2313: Adjust screenshots
  assets/client-apps/nuxeo-drive-release-notes/DT-sessions-history.png
  assets/client-apps/nuxeo-drive-release-notes/DT-sessions-monitoring.png
  assets/client-apps/nuxeo-drive-release-notes/NXDRIVE-2359-after.png
  assets/client-apps/nuxeo-drive-release-notes/NXDRIVE-2359-before.png
  assets/client-apps/nuxeo-drive-release-notes/NXDRIVE-2359.png
  src/client-apps/nuxeo-drive/nuxeo-drive-release-notes.md
Labels: Reviewing

#1638 NXDOC-2244: update licenses page
  src/nxdoc/licenses.md
Labels: Wait before merge

#1639 task NXDOC 2244 update licenses page 2021
  src/nxdoc/licenses.md
Labels: Wait before merge
