Repository nuxeo/doc.nuxeo.com-content, pull requests merged in 2020-09, with the labels that each got.

#1548 NXDOC-2182: Doc update for drive 4.4.5
  assets/client-apps/nuxeo-drive-direct-transfer/direct-transfer-creation.png
  assets/client-apps/nuxeo-drive/drive-notif-upgrade-available.png
  assets/client-apps/nuxeo-drive/drive-notif-upgrade-progress.png
  src/client-apps/nuxeo-drive.md
  src/client-apps/nuxeo-drive/nuxeo-drive-functional-overview/nuxeo-drive-direct-transfer.md
Labels: Reviewed

#1559 Prepare 4.4.5 Drive release
  src/client-apps/nuxeo-drive/nuxeo-drive-release-notes.md
Labels: Wait before merge

#1553 NXDOC-2187: review translations management doc
  src/nxdoc/web-ui/web-ui-tutorials/web-ui-search.md
  src/nxdoc/web-ui/web-ui-tutorials/web-ui-translations.md
  src/nxdoc/web-ui/web-ui-tutorials/web-ui-translations/web-ui-automated-translation-labels.md
  src/nxdoc/web-ui/web-ui-tutorials/web-ui-translations/web-ui-managing-translations.md
Labels: Reviewed, Wait before merge
