Repository nuxeo/doc.nuxeo.com-content, pull requests merged in 2021-01, with the labels that each got.

#1646 NXDOC-2201: add example snippet to enable navigation by UID
  src/nxdoc/web-ui/web-ui-tutorials/web-ui-routing.md
Labels: Wait before merge

#1671 Master - LTS 2021 Release configuration update
  config.yml
Labels: Release LTS 2021

#1674 810: LTS 2021 Release configuration update
  config.yml
Labels: Release LTS 2021

#1673 910: LTS 2021 Release configuration update
  config.yml
Labels: Release LTS 2021

#1672 1010: LTS 2021 Release configuration update
  config.yml
Labels: Release LTS 2021

#1679 NXDOC-2245: Improve custom Docker image build from Nuxeo
  src/nxdoc/nuxeo-server/installation/docker-image.md
  src/nxdoc/nuxeo-server/installation/docker-image/build-a-custom-docker-image.md
Labels: Ready for Review
