Repository nuxeo/doc.nuxeo.com-content, pull requests merged in 2021-04, with the labels that each got.

#1760 NXDOC-2310: Prepare RN page for Salesforce
  src/nxdoc/nuxeo-add-ons/nuxeo-for-salesforce.md
  src/nxdoc/nuxeo-add-ons/nuxeo-for-salesforce/nuxeo-salesforce-release-notes.md
Labels: Reviewing

#1764 NXDRIVE-2463: Document idempotent requests option
  src/client-apps/nuxeo-drive.md
Labels: Ready for Review

#1769 Specify ARM64 macOs support for Nuxeo Drive
  src/client-apps/nuxeo-drive.md
  src/client-apps/nuxeo-drive/nuxeo-drive-faq.md
Labels: Ready for Review

#1765 NXDOC-2233: Add Devcontainer page
  src/nxdoc/nuxeo-tools/nuxeo-devcontainer.md
Labels: Reviewed

#1776 NXDRIVE-2610: TRACE logging level deletion
  src/client-apps/nuxeo-drive.md
Labels: Ready for Review
