Repository nuxeo/doc.nuxeo.com-content, pull requests merged in 2023-12, with the labels that each got.

#2182 NXDOC-2622: release notes for web ui 3.0.29
  src/nxdoc/web-ui/web-ui-release-notes.md
  src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-28.md
  src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-29.md
Labels: Ready for Review, Release LTS 2021

#2183 NXDOC-2624: release notes for web ui 3.1.4
  src/nxdoc/web-ui/web-ui-release-notes.md
  src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-1-3.md
  src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-1-4.md
Labels: Ready for Review

#2168 Update installing-and-setting-up-related-software.md
  src/nxdoc/nuxeo-server/installation/tomcat-server-zip/installing-and-setting-up-related-software.md
Labels: Reviewed

#2175 Update nuxeo-elements-tutorial.md
  src/nxdoc/web-ui/nuxeo-elements/nuxeo-elements-tutorial.md
Labels: Reviewed

#2176 Update nuxeo-retention-functional-overview.md
  src/nxdoc/nuxeo-add-ons/nuxeo-retention-management/nuxeo-retention-functional-overview.md
Labels: Reviewed

#2178 NXP-32157: Fix/simplify Kafka compatibility section
  src/nxdoc/nuxeo-server/installation/compatibility-matrix.md
Labels: Reviewed

#2177 NXP-32157: Upgrade Kafka tested version from 3.3.1 to 3.6.0
  src/nxdoc/nuxeo-server/installation/compatibility-matrix.md
Labels: Reviewed
